// Code generated by jtd-codegen for TypeScript v0.2.0

export interface ClockWrapper {
  clockStandard: ClockStandard;
  images: { [key: string]: string };
}

export enum ClockLayerType {
  BatteryIndicator = 'batteryIndicator',
  DataBar = 'dataBar',
  DataLabel = 'dataLabel',
  DataRing = 'dataRing',
  DateTime = 'dateTime',
  Hand = 'hand',
  Icon = 'icon',
  Image = 'image',
  Text = 'text',
}

export interface ClockLayer {
  /**
   * transparency
   */
  alpha: string;

  /**
   * rotation of the overall layer
   */
  angleOffset: string;

  /**
   * each layer can have user generated names or empty
   */
  customName: string;

  /**
   * fill color ( re used for public various types )
   */
  fillColor: string;

  /**
   * 0 is center : negative left
   */
  horizontalPosition: string;

  /**
   * filenames for images used in the layer
   */
  imageFilename: string;

  /**
   * hide this layer
   */
  isHidden: boolean;

  /**
   * 1.0 is normal
   */
  scale: string;
  type: ClockLayerType;

  /**
   * 0 is center : negative up
   */
  verticalPosition: string;

  /**
   * 0 is bottom higher is top. layering
   */
  zIndex: number;
}

export interface ClockStandard {
  layers: ClockLayer[];
  title: string;

  /**
   * always 1.0
   */
  version: '1.0';
}
